Code-4-Community/speak-for-the-trees-frontend

src/components/map-page-components/map-view/MapView.tsx

[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/pulses/925424069)
What benefit does this bring to the end user? Or, what benefit does this bring to developers working in the codebase?
- (External) Allows users to identify neighbourhoods/areas from the overlay, which was previously hidden by the green overlay on the maps api.
- (Internal) Dynamic function that adds names based on features in the data layer, and can adjust based on additions/deletes of areas on the map. Easily maintained keyValuePair interface to track shortHands.
Describe the changes required and any implementation choices you made to give context to reviewers.
- Chose to implement an array of Markers to toggle visibility
- Implemented a function within loadGeoJson to ensure that the data layer …

Neighbourhood Names and shortHands

---

src/auth/ducks/types.ts
src/components/linkcarousel/LinkCarousel.tsx
src/components/signup-form/SignupForm.tsx
src/containers/signup/Signup.tsx

[Monday.com Ticket](https://code4community-team.monday.com/boards/XXXXXXXX/pulses/XXXXXXX)
What benefit does this bring to the end user? Or, what benefit does this bring to developers working in the codebase?
Describe the changes required and any implementation choices you made to give context to reviewers.
Provide screenshots of any new components, styling changes, or pages.
What steps did you take to verify your changes work? These should be clear enough for someone to be able to clone the branch and follow the steps themselves.

Improve signup page

---

src/auth/test/authClient.test.ts
src/auth/test/thunks.test.ts
src/components/landing-tree-stats/LandingTreeStats.tsx
src/components/leaderboard/leaderboard-tab/LeaderboardTab.tsx
src/components/map-page-components/map-view/MapView.tsx
src/components/nav-bar/NavBar.tsx

[Monday.com Ticket](https://code4community-team.monday.com/boards/XXXXXXXX/pulses/XXXXXXX)

Passed eslint checks

---

src/components/LinkButton.tsx
src/components/window-dimensions.tsx

We are missing an interface on the window dimension utility functions. 
Adds an interface for window dimensions. 
No visual changes. 
Code builds.

Add Interface to Window Dimensions

---

src/api/protectedApiClient.ts
src/api/test/protectedApiClient.test.ts
src/components/navBar/index.tsx
src/containers/adminDashboard/index.tsx
src/containers/settings/index.tsx

[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/pulses/925294524)
This PR connects the remaining user settings routes to the frontend. This will allow users to delete their accounts, change usernames, and it will allow admins to change the privilege levels of other users
Added new routes to the protected api routes file, created a new test file and directory, and added to the settings and admin forms pages.
No new styling
I created tests for the cases where the routes work as planned. I could not figure out how to handle errors so that will be an iteration onto this PR. I also tested the change_privilege form with one the the users in my local backend.

Settings routes

---

src/api/protectedApiClient.ts
src/api/test/protectedApiClient.test.ts
src/components/teamMember/index.tsx
src/containers/availableTeams/ducks/actions.ts
src/containers/availableTeams/ducks/reducer.ts
src/containers/availableTeams/ducks/selectors.ts
src/containers/availableTeams/ducks/thunks.ts
src/containers/availableTeams/ducks/types.ts
src/containers/teamPage/ducks/actions.ts
src/containers/teamPage/ducks/reducer.ts
src/containers/teamPage/ducks/selectors.ts
src/containers/teamPage/ducks/thunks.ts
src/containers/teamPage/ducks/types.ts
src/containers/teamPage/index.tsx
src/store.ts

[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1133710328)
This PR connects the team routes to the redux store and includes unit tests for these routes respond as expected. These routes will allow the user to access team data from the backend and stores it locally. It also lays the ground work for connecting that data to the frontend pages where users can view their team data as well as make requests such as joining teams.
I added routes to the protectedApiRoutes file. Because the routes have teamIds within them, I defined most routes as functions which take in numbers and return the correct routes as strings. 
For the ducks files and testing, I followed the pattern of the previous redux tickets.
N/A
I made sure each of the unit tests …

Teams routes

---

src/App.tsx
src/auth/ducks/types.ts
src/components/navBar/index.tsx

[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/pulses/1185008418)
Allows super admins to interact with the front end.
Super admins have access to the same routes as admins.
Ensured super admins could log in and go to all pages, including the admin dashboard.

Add Super Admin Privilege Level

---

src/components/navBar/index.tsx

[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1258029135)
Forces refresh on logout so users are auth-redirected to login and can't see user data of the last person logged in.
Force refresh after dispatching logout with `history.go(0)`. 
Logged in and tested logout on various pages.

Force Refresh on Logout

---

src/api/protectedApiClient.ts

[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1276131280)
The reservation requests no longer throw 400 errors because the requests have the correct case 
just changed all the instances of "_id" to "ID"
No styling
Confirmed with Vrushali that this fixed the error

Reservation block and team id is case sensitive

---

src/App.tsx
src/components/mapPageComponents/mapView/index.tsx
src/components/treePopup/index.tsx
src/utils/isCheck.ts
src/utils/test/isCheck.test.ts

[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1224885844)
Adds tree popup to map so users can easily navigate to tree pages.
MapView
- created a [custom popup](https://developers.google.com/maps/documentation/javascript/examples/overlay-popup)
- changed `useEffect` dependencies so the map doesn't reload whenever the popup is added/popup data is changed (or whenever the reservation modal is shown) by
- making `markersArray` a constant within `useEffect`
- making the dependencies `mapRef.current` and `treePopupRef.current` rather than the refs themselves. Since the refs update after DOM loads, created useEffects to update `mapElement` and `treePopupElement` as needed
TreePopup
- is not visible by default (otherwise would show on map before …

Connect Tree Popup

---

src/api/apiClient.ts
src/api/protectedApiClient.ts
src/api/test/apiClient.test.ts
src/api/test/protectedApiClient.test.ts

Closes #97.
Removed catch clauses from apis and added tests for each possible error.
Ensured tests passed.

Proper Error Handling

---

src/containers/myTrees/test/selectors.test.ts
src/containers/treePage/ducks/thunks.ts
src/containers/treePage/ducks/types.ts
src/containers/treePage/test/reducers.test.ts
src/containers/treePage/test/selectors.test.ts
src/containers/treePage/test/thunks.test.ts

Adding tests to the redux behavior on the tree pages. Adds another check to ensure that any changes to tree pages and tree page routes on the frontend do not change or break the data we expect.
Created tests for the selectors, reducers, and thunks on the tree pages. Followed the patterns on the auth tests.
No styling
I ran the new tests and ensured that they all passed before opening this PR. Tried to make sure I handled a variety of cases

added tests for tree page requests

---

src/assets/content.tsx
src/components/treePopup/index.tsx

[ClickUp Ticket](https://app.clickup.com/t/1nucrmd)
Updates the link to request the city to plant a tree.
Updated the link, put it in `content.tsx` so we can reuse it in future tickets (ex. link on an open site's tree page) and update it easily
Ran the frontend, made sure the popup linked to the appropriate site.

Update City Tree Planting Request Link

---

src/auth/ducks/thunks.ts
src/auth/test/thunks.test.ts
src/components/entryList/index.tsx
src/components/forms/signupForm/index.tsx
src/components/greetingContainer/index.tsx
src/components/mapComponents/mapPageComponents/siteLegend/index.tsx
src/components/themedComponents/index.tsx
src/components/treePopup/index.tsx
src/components/windowDimensions/index.tsx
src/containers/login/index.tsx
src/containers/signup/index.tsx
src/containers/treePage/index.tsx

[ClickUp Ticket](https://app.clickup.com/t/2my7fvm)
Improves the user experience by removing unnecessary scroll bars and improving reflexive styling. Also fixed the line not extending across the entire tree popup.
- AntD's components have been too rigid for reflexive styling. I replaced Rows, Cols, and Lists with flex divs. 
- From there, it's mostly css changes to height/width/margins/etc. to make everything look good. 
- Used css media queries at times to simplify styling instead of hooking into the state as we've been doing - for the future, we'll reserve use of the hook to component layouts rather than styled component styling.
- Use message instead of Alerts to inform users of login/signup errors - this makes styling much easier and avoids the error we had where it's impossible to …

Scroll Bars and Reflexive Styling

---

.gitignore
package-lock.json
speak-for-the-trees-frontend.iml
src/auth/ducks/selectors.ts
src/containers/home/index.tsx

added reports link and display box to the homepage if the user is an admin by adding conditionals(ternary operators)
If the given user is an admin, then append REPORT to the list of display, otherwise, show the default display.

added reports link to homepage for admins

---

src/containers/adminDashboard/index.tsx
src/containers/settings/index.tsx

[ClickUp Ticket](https://app.clickup.com/t/29xdaxz)
Cleaner UI experience and more design consistency across different pages.
Made delete account container on settings page with bottom margin for desktop, and moved the delete button to the button on mobile. Fixed top margin on admin dashboard.
<p float="left">
</p>
<p float="left">
</p>
<p float="left">
</p>
Visually inspected modified pages on desktop and mobile.

Page Layout Changes

---

src/components/tables/adoptionReportTable/index.tsx
src/components/tables/stewardshipReportTable/index.tsx

[ClickUp Ticket](https://app.clickup.com/t/23k0y5h)
Allows admins to review adoption and stewardship reports by neighborhoods.
Added filters using AntD table props `filters` and `onFilter`.
Tested locally on desktop and mobile.

Add neighborhood filter

---

src/components/forms/loginForm/index.tsx
src/components/slideDown/index.tsx
src/containers/landing/index.tsx

(No relevant ClickUp ticket)
3 minor frontend fixes to make the website more user-friendly.
The 3 changes are:
- Change the cursor on the legend slide button on hover
- Change the introduction modal button background color on hover
- Make the username and password text inputs in the login page separate rows on desktop devices
1. Change the cursor on the legend slide button on hover
- <img src="https://user-images.githubusercontent.com/33704204/204904942-b8e38958-8abc-4a3b-877d-ed72588c7acc.png" width="600">
2. Change the introduction modal button background color on hover
- Before hover: ![image (1)](https://user-images.githubusercontent.com/33704204/204905655-5e1f6e28-cc01-4a54-903e-3d0fc5848f15.png)
- On hover: ![image (2)](https://user-images.githubusercontent.com/33704204/204905697-862 …

Misc. frontend fixes

---

src/components/shareMenu/index.tsx

No relevant ClickUp ticket
Fix typo in Twitter share link
Fix typo in Twitter share link

Fix Twitter link typo

---

src/components/treeActivity/index.tsx
src/containers/treePage/ducks/selectors.ts
tslint.json

Add logging to track down cause of stewardship activity performed date bug

---

src/api/protectedApiClient.ts
src/components/treeActivity/index.tsx
src/containers/treePage/ducks/selectors.ts
src/containers/treePage/index.tsx
tslint.json

[ClickUp Ticket](https://app.clickup.com/xxxxxxxx/v/b/li/xxxxxxxxx)

Revert all logging to track down stewardship activity recorded date bug

---

.github/pull_request_template.md

Add checklist to PR template

---

src/auth/axios.ts
src/components/infoCard/index.tsx
src/components/mapComponents/mapLegend/content.ts
src/components/mapComponents/maps/mapWithPopup/index.tsx
src/components/treeActivity/index.tsx
src/containers/faq/content.tsx
src/containers/myTrees/test/selectors.test.ts
src/containers/reports/ducks/selectors.ts
src/containers/reports/index.tsx
src/containers/treePage/test/selectors.test.ts

Format files

---

src/api/protectedApiClient.ts
src/components/forms/ducks/types.ts
src/components/forms/uploadSitesForm/index.tsx

Fix broken addSites route and add AddSitesRequest DTO

Fix addSites bug and add AddSitesRequest DTO

---

src/App.tsx
src/containers/email/index.tsx

[ClickUp Ticket](https://app.clickup.com/t/1tr7bn1)
Set up emailer page

Set up email page

---

src/components/forms/uploadSitesForm/index.tsx

Add addSites CSV template download link

---

src/App.tsx
src/auth/test/selectors.test.ts
src/components/mapComponents/maps/mapWithPopup/index.tsx

[ClickUp Ticket](https://app.clickup.com/t/2nur637)

Test isAdmin selector and use throughout application

---

src/components/mapComponents/maps/mapWithPopup/index.tsx

Move mapTypeControl down on mobile

---

src/App.tsx
src/i18n/en/index.ts
src/utils/test/stringFormat.test.ts

Add tenant env variable to Cambridge

---

src/containers/landing/index.tsx

Make Cambridge logo smaller in welcome modal

---

src/containers/treePage/ducks/types.ts

Add cambridge site entry fields

---

craco.config.js
src/assets/links.tsx
src/components/mapComponents/constants.tsx
src/components/treeInfo/index.tsx
src/containers/landing/index.tsx
src/utils/colors.tsx
src/utils/isCheck.ts

Add isSFTT() and change default city for Cambridge

---

src/utils/test/treeFunctions.test.ts
src/utils/treeFunctions.tsx

Fix tree common name casing in default share site text

---

src/api/test/protectedApiClient.test.ts

Add specs for send email and filter sites routes

---

src/api/protectedApiClient.ts
src/components/forms/sendEmailForm/index.tsx
src/containers/email/index.tsx
src/containers/reports/test/selectors.test.ts

Fix filter sites URL when common names filter is applied

---

src/components/mapComponents/mapPageComponents/siteLegend/index.tsx
src/components/mapComponents/maps/treeMap/index.tsx
src/components/themedComponents/index.tsx
src/containers/landing/index.tsx

refactor site legend to mobile

---

src/App.tsx
src/auth/ducks/thunks.ts
src/components/mapComponents/ducks/test/thunks.test.ts
src/components/mapComponents/ducks/thunks.ts

Ah.logout fix

---

README.md

Trigger Cambridge redeploy

---

.github/pull_request_template.md

utilize GH projects + update checklist

---

src/components/treePageHeader/index.tsx
src/containers/treePage/index.tsx

fix site page to update with new tree name

---

amplify.yml

Change build command in amplify.yml from npm to yarn

---

.github/pull_request_template.md

Resolves N/A
Updates the commands in the PR template's checklist from npm to yarn

Update PR template checklist from npm to yarn

---

.github/workflows/node.js.yml

Ah.update build steps

---

src/containers/treePage/index.tsx

Temporarily hide tree benefits section

---

src/components/treePage/treeBenefits.tsx
src/containers/treePage/ducks/types.ts
src/containers/treePage/index.tsx
src/i18n/en/treePage/treePage.json

unblock tree benefits + null checking

---

src/components/navBar/translationDropdown.tsx
src/i18n/i18n.ts

add lang to localstorage to persist across tabs

---

src/components/forms/sendEmailForm/content.ts
src/components/forms/sendEmailForm/index.tsx
src/containers/email/index.tsx

Ah.emailer fix

---

src/components/forms/changePrivilegeForm/index.tsx

allow demoting to standard
