- README.md
The coveralls badge was for the frontend-scaffold, switched the badge to represent coverage of this repo
> replaced coveralls badge with the one for the sftt repo

- src/App.tsx
- src/auth/ducks/types.ts
- src/auth/token.tsx
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/pulses/1016839076)
Ensures only users with proper privilege levels can see protected pages.
- Updated `PrivilegeLevel` and `getPrivilegeLevel()`
- Use switch case to declare routes for each privilege level type
- If the user lacks the appropriate privilege level for a path, redirects using `Redirect`
Ran frontend and backend locally, tried each path and checked it went to the appropriate place after:
- not logging in
- logging in as a standard user
- logging in as an admin
> Authentication for Protected Pages

- src/App.tsx
- src/components/leaderboard/leaderboardSpace/index.tsx
- src/components/leaderboard/leaderboardTab/index.tsx
- src/components/leaderboard/leaderboardTabs/index.tsx
- src/components/leaderboard/types.ts
- src/components/linkCarousel/index.tsx
- src/containers/availableTeams/index.tsx
- src/containers/teamLeaderboard/ducks/selectors.ts
- src/containers/teamLeaderboard/index.tsx
- src/containers/volunteerLeaderboard/ducks/selectors.ts
- src/containers/volunteerLeaderboard/index.tsx
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/pulses/926124762)
This PR allows users to view which teams are accepting new people and allows the user to click a button to view the pages of those teams
Created an `AvailableTeams` component which has a header, pagination, and the collapse with the teams
Moved a part of `LeaderboardTabs` to its own component, `LeaderboardSpace` as the main section of the page in order to reuse some of the logic for a paginated leaderboard. Added an optional `large` prop which is a boolean that sets the size of the leaderboard items.
There is an empty button on each team item right now which will eventually be a link to the individual team page
Used dummy data to verify that the styling was correct. Used dummy data for a …
> created available teams page

- src/App.tsx
- src/components/goalInfo/index.tsx
- src/components/landingTreeStats/index.tsx
- src/components/teamMember/index.tsx
- src/components/test/landing-tree-stats.test.tsx
- src/containers/teamPage/ducks/types.ts
- src/containers/teamPage/index.tsx
- src/utils/stringFormat.tsx
- src/utils/test/stringFormat.test.ts
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/pulses/926124580)
Creates the team page where users can view a team's members and goals and apply to join.
- Created a `types.ts` to match backend
- Created `TeamPage` container, which uses a list to display all members in the team and a collapse to display goals
- info about members (username, role) is formatted in `TeamMember` component
- team leader has a crown next to their username
- expanding a collapse panel shows info about the goal, which is formatted in `GoalInfo` component
- the first goal in the data is expanded by default
- "Incomplete" is displayed by the collapse panel's dropdown if the goal's `completion_date` is `null`
- Added route for individual team page
- Created `getDateString` to format …
> Individual Teams Page

- src/components/treePopup/index.tsx
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/pulses/926131646)
Creates popup to let viewers see more information about a tree/navigate to that tree's page on the map.
Created the popup component to be linked to the map as a [custom popup](https://developers.google.com/maps/documentation/javascript/examples/overlay-popup#all) (rather than an info window to allow for increased customization)
- tried using AntD's popover but this doesn't work well with the map for placement and toggling visibility
- `popRef` is for integration with the map
Visually confirmed it matched the designs, placed it onto the map blocks layer to make sure it would work well once the sites are added
> Create Tree Popup

- src/store.ts
Sometimes auth is weird around refreshes. 
Shortens the throttle to 1 second, not 10, on saving the store to localstorage. 
Applies the token to axios regularly.
> Reduce throttle, apply tokens regularly

- src/components/loginForm/index.tsx
- src/components/signupForm/index.tsx
- src/containers/login/index.tsx
- src/containers/signup/index.tsx
- src/utils/formRules.tsx
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/pulses/1012460652)
Prevents form fields from being cleared on window resize.
- Used `Form.useForm` to keep form instance consistent across forms rendered on different window types
- Passed `windowType` to forms as a prop rather than having both pages and forms use the `useWindowDimensions` hook (less event listeners)
No styling changes.
Ran locally, input values into form fields and resized the browser past each breakpoint to check that
- layout updated according to designs
- values did not clear past breakpoints
> Keep Login/Signup Form Values on Resize

- src/api/apiClient.ts
- src/api/test/apiClient.test.ts
- src/components/mapPageComponents/ducks/actions.ts
- src/components/mapPageComponents/ducks/reducer.ts
- src/components/mapPageComponents/ducks/test/reducers.test.ts
- src/components/mapPageComponents/ducks/test/thunks.test.ts
- src/components/mapPageComponents/ducks/thunks.ts
- src/components/mapPageComponents/ducks/types.ts
- src/components/mapPageComponents/mapPage/index.tsx
- src/components/mapPageComponents/mapView/index.tsx
- src/components/mapPageComponents/mobileMapPage/index.tsx
- src/containers/landing/index.tsx
- src/containers/reservations/index.tsx
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/pulses/1247539229)
Connects get sites in geojson route so that site information can be used, ex. in displaying trees on the map.
- Added route to ApiClientRoutes and tested successful request
- Added siteGeoData to the MapGeoDataReducerState, created necessary ducks, tested reducers and thunks
- Added sites to MapViewProps (setup for ticket to make the tree map)
Made sure unit tests passed
> Connect Sites Geojson Route

- src/api/protectedApiClient.ts
- src/api/test/protectedApiClient.test.ts
- src/components/forms/changePrivilegeForm/index.tsx
- src/components/forms/ducks/types.ts
- src/containers/adminDashboard/index.tsx
- src/utils/formRules.tsx
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1258123891)
Adds validation and feedback to admin forms for a more user-friendly experience.
- Created a separate component for the change privilege level form
- admins can make other users admins (opened ticket for backend to prevent admins from demoting super admins)
- super admins can make other users standard, admins, or super admins
- Removed catch in protectedApiClient so the error can be caught in the component and used to give feedback to the user
- Removed download team data button - team data won't be a feature in the next release of the site (revisit this in the fall)
Admin Form
Super Admin Form
Feedback Messages
Used form as an admin and super admin to change users' privilege …
> Add Validation and Feedback to Admin Forms

- src/api/apiClient.ts
- src/api/protectedApiClient.ts
- src/api/test/apiClient.test.ts
- src/api/test/protectedApiClient.test.ts
- src/components/stewardshipForm/index.tsx
- src/containers/treePage/ducks/actions.ts
- src/containers/treePage/ducks/protectedReducer.ts
- src/containers/treePage/ducks/reducer.ts
- src/containers/treePage/ducks/selectors.ts
- src/containers/treePage/ducks/thunks.ts
- src/containers/treePage/ducks/types.ts
- src/containers/treePage/index.tsx
- src/store.ts
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1185039378)
This PR allows users to view the stats about a particular tree as well as the stewardship activities that have been performed. This also allows the user to adopt, unadopt, and perform stewardship activities on those trees
Created the api routes, reducers, thunks, and selectors that retrieve data from the backend, put it in redux, and display that data on the frontend. I also made changes to the treepage that allowed it to work with these changes
Double checked the results of these routes in postman. Made sure those calls gave the same results from the UI. Currently the unadopt does not work in the backend so once that is fixed there may be some fixes needed. The get routes have …
> connecting stewardship and get site routes

- src/components/pageHeader/index.tsx
- src/containers/home/index.tsx
There was a console warning about using camel case in dom props. This change removes that warning
I simply changed the subtitle prop from camelCase to lowercase
That particular warning is gone
The pageheaders still display their subtitles with the correct colors
> made subtitlecolor prop lower case to remove react warning

- src/api/protectedApiClient.ts
- src/components/mapPageComponents/ducks/types.ts
- src/components/mapPageComponents/mapView/index.tsx
- src/containers/treePage/ducks/types.ts
- src/containers/treePage/index.tsx
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1263481139)
This PR gives different colors to trees based on their attributes. Young trees are blue and adopted trees are red
I added the planting date and adopter id to the site feature type and added a condition to the styling of the sites on the map that selects the correct color
I used postman to make sure the planting date and adopter id values were coming back as expected. The changes are cosmetic so I was able to see the change in colors on the map
> added tree colors to map

- src/components/forms/ducks/types.ts
- src/components/forms/stewardshipForm/index.tsx
- src/components/mapPageComponents/mapView/index.tsx
- src/components/pageHeader/index.tsx
- src/components/treeActivity/index.tsx
- src/components/treeInfo/index.tsx
- src/containers/treePage/ducks/selectors.ts
- src/containers/treePage/index.tsx
- src/utils/stringFormat.tsx
- src/utils/test/stringFormat.test.ts
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1266458984)
Makes the page user-friendly on mobile and improves styling across devices.
Styling Changes
- Generally tried to fill the page more since we don't have a tree photo, allow for scrolling when there's overflow
- Changed format of dates for stewardship records:
- month is in shorthand to fit the container better
- suffix after day (`st`/`nd`/`rd`/`th` depends on the day)
- Address includes city and zip code (even if street address is not available, these will be displayed, every site has this information)
- Capitalized tree names
- Followed the standard format for changing styling based on window dimensions.
Functionality
- Users can only input activities done that day or two weeks …
> Update Tree Page Styling Across Window Types

- src/App.tsx
- src/components/mapPageComponents/mapView/index.tsx
- src/components/treeInfo/index.tsx
- src/containers/home/index.tsx
- src/containers/treePage/ducks/reducer.ts
- src/containers/treePage/ducks/selectors.ts
- src/containers/treePage/ducks/types.ts
- src/containers/treePage/index.tsx
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1323610260)
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1331275997)
Prevents users from accessing pages that are still in development and disables the adopt button if a tree has already been adopted.
- Commented out routes we won't be using yet and a few related things (ex. pagination)
- Added `adopter` to SiteEntry to check if a site has an adopter
Updated home links
Disabled adopt button
Tried accessing the blocked routes and ensured was redirected to page not found
> Accessible Routes and Disable Adopt Button

- src/components/navBar/index.tsx
- src/components/treePopup/index.tsx
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1401865519)
[Monday.com Ticket](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1398345228)
Formatting fixes to map popups on the mapView look nicer. Removes the unnecessary horizontal and vertical scrolling. Also changed the alignment of the nav bar logos so they do not get cut off when a screen is short
I added a min-height to the tree popups to set their size and I removed the max height to prevent text from being cut off. The common name and address already have length limits enforced in the database so there is not a concern about a huge chunk of text in the popup. 
For the navbar I changed the row alignment from bottom to middle and set a min height for the …
> changed navbar alignment and popup dimensions

- src/components/treeInfo/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/1fqtbjh)
Allows tree pages to have headers if they have no common name or species.  
Changed logic for displaying header.  Formerly header was dependent on common name existing, replaced with ? operator. 
Compared https://map.treeboston.org/tree/3215900 and http://localhost:3000/tree/3215900: former has a blank header where local version contains address information
> Displays information on tree page if common name is unknown

- src/auth/axios.ts
[ClickUp Ticket](https://app.clickup.com/t/250xh4q)
There's an issue where some requests (I think those that aren't dispatched) result in the error "Missing required request header: X-Access-Token" unless made immediately after login.
Error occurs because the access token in store isn't applied to the header for each request. Existing code attempts to do this after login by setting the axios instance config defaults
`AppAxiosInstance.defaults.headers['X-Access-Token'] =  response.accessToken;`
but the token is not appplied to every request, only the next request after login.
This PR creates an interceptor that intercepts each axios request, gets the access token from store, and applies the header (if user is logged in).
> Missing X-Access-Token

- src/components/mapComponents/logic/event.ts
- src/components/mapComponents/logic/style.ts
[ClickUp Ticket](https://app.clickup.com/t/28ry9d3)
SFTT noticed the neighborhoods of the map all had the same opacity.
Found the bug was caused because the name passed to `getProperty` did not exist, making the method return undefined and thus setting the opacity to the default for all neighborhoods. This is a result of the updated back end naming conventions. Changed names passed to `getProperty` to camelCase to reflect the change from snake_case in the back end.
Properly styled neighborhoods:
Visually confirmed the neighborhood opacities are correct.
> Reflect updated back end naming convention

- src/auth/axios.ts
- src/auth/ducks/thunks.ts
- src/auth/test/thunks.test.ts
- src/store.ts
[ClickUp Ticket](https://app.clickup.com/t/1x52pz7)
Ensures the access token is refreshed or the user is logged out when access token expires.
Previously, our way of refreshing never actually updated the store with the fresh access token–instead, axios would always catch the expired access token error, get a new access token, and apply that token to the next call (re-making the original request). This ticket creates a refresh thunk to update the Redux store via dispatch. The axios response interceptor uses the refresh thunk and logout thunk instead of calling authClient directly to ensure the store is updated appropriately.
Wrote tests for the new refresh thunk and ran the front end/back end to check that refresh worked after the access token expired.
> Refresh Updates Redux Store

- src/components/copyText/index.tsx
- src/components/copyText/test/copyText.test.tsx
- src/components/tables/adoptionReportTable/index.tsx
- src/components/tables/stewardshipReportTable/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/28t1r2h)
Allows admins to easily copy the emails listed in the reports.
Created a new component, ClickableText, that (by default) copies the displayed text to the clipboard.
- Uses the [ClipboardAPI](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API), which is not supported on Internet Explorer - users will be notified if their browser doesn't support copying
- Takes `onCopy` as a prop for extension + testing purposes
Wrote tests to check the logic and error handling.
> Copy email in reports to clipboard

- src/components/mapComponents/maps/mapWithPopup/index.tsx
- src/components/treePopup/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/1x52qae)
Open the tree page in a new tab after clicking "More Info" on the map popup.
Pass in "_blank" as `target`. The change that led to this bug was through #113 (just a little confused as to why this change was initially required - would this ticket break how the popup and return button function on mobile?).
Clicking the "More Info" button on the tree popup opens tree page in a new tab (at least on desktop).
Clicking on the "Return to Tree Map" button redirects to the main page with the map with the right location and street-level zoom.
Tested that the tree page opens up in a new page and that clicking the "Return to Tree Map" button redirects to the map page with the correct location. Not tested on mobile.
> Open tree page in a new tab

- src/components/mapComponents/constants.tsx
- src/components/mapComponents/maps/treeMap/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/27pkmw3)
Remove names of buildings and other text so that the map mostly just displays street and park names.
Change the options for the map so that it doesn't display names of POIs (points of interest) except for parks.
Visually tested that the map mostly only displays street and park names on both desktop and mobile in Chrome and Firefox.
> Display only streets and parks in map

- src/assets/content.tsx
- src/containers/forgotPassword/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/1gewz96)
Improve the forgot password page so that it displays appropriate messages instead of alert popups and console logs when the password reset request is successful or not. Upon a successful request, update the page to prevent the user from submitting multiple requests.
Initial screen:
User submits non-existent email:
User submits correct email:
Verify that the messages shown are as expected when the user submits incorrect and correct email addresses.
> Improve forgot password page

- src/App.test.tsx
- src/auth/axios.ts
- src/auth/ducks/thunks.ts
- src/auth/test/authClient.test.ts
- src/auth/test/axios.test.ts
- src/auth/test/reducers.test.ts
- src/auth/test/selectors.test.ts
- src/auth/test/thunks.test.ts
- src/containers/login/test/login.test.tsx
- src/containers/reports/index.tsx
- src/utils/stringFormat.tsx
- src/utils/test/stringFormat.test.ts
[ClickUp Ticket](https://app.clickup.com/t/29a81x7)
Doesn't show auth error after successful refresh and properly logs out user if refresh token is expired. Adds an error type to make handling errors easier.
Essentially made some fixes to responseErrorInterceptor - will leave comments.
- Wrote tests for the error response interceptor and ensured they passed
- Manually checked that refresh/force logout worked (you can make this easier to test by changing `expiration_ms_refresh` and `expiration_ms_access` in the backend)
> Auth Error Interceptor

- antd.customize.less
- public/index.html
- src/components/treePopup/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/1geybt7)
Aesthetic change
Imports Montserrat from Goole Fonts and sets AntD theme's font-family to Montserrat.
Visually checked the font updated and looks good on each page.
> Set font to Montserrat

- src/api/protectedApiClient.ts
- src/api/test/protectedApiClient.test.ts
- src/components/forms/signupForm/index.tsx
- src/components/themedComponents/index.tsx
- src/containers/adminDashboard/index.tsx
- src/containers/signup/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/27pm2f2)
Allows admins to create child accounts.
Paired with @Tvcz 
Added the route to `protectedApiClient` and added a create child account form to the admin dashboard (reusing signup form).
Admin Dashboard (Desktop)
Admin Dashboard (Mobile)
Added tests for `protectedApiClient` and made sure error messages and success messages showed up appropriately when running locally.
> Create Child Account Form

- src/components/adoptionDirections/index.tsx
- src/components/mapComponents/constants.tsx
- src/components/mapComponents/mapLegend/index.tsx
- src/components/mapComponents/mapPageComponents/mobileLandingBar/index.tsx
- src/components/mapComponents/mapPageComponents/siteLegend/index.tsx
- src/components/mapComponents/maps/mapWithPopup/index.tsx
- src/components/mapComponents/maps/selectorMap/index.tsx
- src/components/mapComponents/maps/treeMap/index.tsx
- src/components/navBar/index.tsx
- src/components/navBar/test/navBar.test.tsx
- src/components/slideDown/index.tsx
- src/components/themedComponents/index.tsx
- src/containers/landing/index.tsx
- src/containers/myTrees/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/27pkxm1)
Makes it easier to view and interact with maps, especially on mobile, allowing the use of one-finger map movement and reducing the obtrusiveness of overlayed map elements. The use of slide-downs allow for more of the map to be visible on mobile.
- Changed map options for gestureHandling to "greedy" on applicable maps.
- Changed SlideDown to fit on screen properly and extended its use on mobile for a better user experience.
- Changed search bar size on mobile to allow for practical use.
- Changed tablet view to more closely align with mobile rather than desktop for maps. 
<p float="left">
</p>
<p float="left">
</p>
<p float="left">
</p>
<p float="left">
</p>
<p float="left">
</p>
<p float="left">
</p>
<p float="left">
</p>
Visually …
> Mobile Map Visual Updates

- src/components/slideDown/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/29xdaqp)
Makes slidedown button bigger on mobile when it's down so it's easier to use on mobile browsers.
- Conditional styling of slidedown button
Visually confirmed using Google Dev tools and iPhone
> Mobile Slidedown

- src/components/treeInfo/index.tsx
- src/utils/formRules.tsx
[ClickUp Ticket](https://app.clickup.com/t/29xbk00)
Change `zipCodeRules` to allow sites to be created/edited with a 5-character numerical zip code (instead of 4). Will update the database so that all zip codes are 5 characters long when this PR gets merged.
Change `zipCodeRules`  so that zip codes must be 5-character numeric values. Also, noticed that there's no input validation in the frontend on submit. The neighborhood dropdown also doesn't display the correct option. Will handle both in separate PRs.
Verified that the zip code field is green only when given a valid input (i.e. 5-digit number) by testing various cases (e.g. 'a', '1234', '1234a', '123456').
Verified that the zip code updates correctly when clicking on the submit button.
> Fix 4-character Zip Codes

- src/components/mapComponents/mapPageComponents/mapPage/index.tsx
Increase width of the MyTrees sidebar so that both the More Info and Edit Site Page buttons are shown in a single row (only an issue with admin users). Bug introduced in #147 (this is on me)
Change the width of the sidebar from 20vw to 22wv
Before:
After:
Checked that the buttons are rendered correctly in both desktop, tablet, and mobile devices
> Increase MyTrees sidebar width for desktop devices

- src/components/treeInfo/index.tsx
- src/containers/treePage/ducks/selectors.ts
- src/containers/treePage/index.tsx
Modified the tree page to do some null checks on the first site entry, in case the site in question has no site entries. 
In the case that a site does not have site entries, it is treated as if there is no tree present at that site.
[ClickUp Ticket](https://app.clickup.com/t/2rw2w3n)
No change for end-user, but now the console is less clogged with errors that don't convey any additional information.
How console would appear previously:
Example of previously erroring site now working:
No error in console:
Checked whether the tree pages for a few sites (ids 3331222, 3331216, 3331217, 3331218) which had no site entries in the dev database `site_entries` table now loaded without any errors in the console.
> Got rid of no site entries bug on tree page

- src/components/forms/ducks/types.ts
- src/components/forms/updateSiteForm/index.tsx
- src/containers/sitePage/index.tsx
- src/containers/treePage/ducks/types.ts
- src/containers/treePage/test/selectors.test.ts
- src/containers/treePage/test/thunks.test.ts
Set the default value for the radio buttons in the add site entry form to be the value of the previous (i.e. latest) entry for that site.
Turn `status` into enum `SiteEntryStatus` from `string` and replace the status text field with a radio button.
The default values for all of the radio buttons are `false` with the exception of `status`, which is `null`.
Create an enum of three values that match the three possible values for `status` (i.e. Alive, Dead, or Dead but standing). If the status radio button isn't selected, the status will be set to `null`.
Check that the default values for the radio buttons are correct both when `latestSiteEntry` is and isn't given (including in the `/admin` page).
> Default form options to previous site entry and turn status input field into radio button

- src/containers/landing/index.tsx
No relevant ClickUp ticket
Hide the legend slider on the landing page by default on mobile and tablet devices so that the slider doesn't hide most of the map when users initially visit the landing page.
Hide the legend slider on the landing page by default on mobile and tablet devices.
(The map isn't displaying atm but that's ok for now)
Visually verified that the legend slider is initially closed when visiting the landing page on mobile and tablet devices. Visually verified that the legend slider initially stays open on desktop devices.
> Hide the legend slider on the landing page by default

- src/components/forms/editTreeNameForm/index.tsx
- src/components/treePageHeader/index.tsx
- src/containers/treePage/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/862j171zh)
1. Default the value of site name text input to be the current name so that the user won't have to type the entire site name when changing just a few characters
2. Refresh the page when the user changes the name of a site so that the user sees that the site name was changed without having to manually refresh the page
1. Set the default value of the text input in `EditTreeNameForm` to be the current tree name, if applicable
2. Use the `useDispatch` hook to get the updated site data and thus trigger a re-render of the component
Visually verified that the default value of the tree name input is the current site name both when the site has and doesn't have a name
Tried changing the site name to arbitrary text (including empty text to …
> Default site name input to current name and refresh page on name change

- src/components/navBar/navMenu/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/36gw2rk)
Increase clickable area on the profile dropdown menu so that users will be able to click on some of the menu items (especially "My Trees" and "Admins") more easily.
Make the menu items in the dropdown take up 100% of their parents' widths.
Note: the purpose of the background colors are just to visually see where the clickable areas for each menu item are and are not shown to users. For the first three menu items, the red areas are the clickable areas and for the last menu item, the green area is its clickable area.
Added background colors to make sure that the clickable areas increased and manually clicked on each menu item to ensure that the clickable areas are, in fact, clickable.
> Increase clickable area on profile dropdown

- src/components/forms/constants.ts
- src/containers/adminDashboard/index.tsx
- src/containers/sitePage/index.tsx
Round latitude and longitude to the nearest 6 decimals when moving the map pin
> Round lat/lng when moving map pin in add/edit site forms

- src/api/protectedApiClient.ts
- src/api/test/protectedApiClient.test.ts
- src/components/treeInfo/index.tsx
- src/containers/treePage/index.tsx
[ClickUp Ticket](https://app.clickup.com/t/1dk46ne)
Allow admin users to force unadopt a site (even though showing the adopter's email is part of this ticket, I don't think it's worth it given that it can (relatively easily) be done through the reports page)
Add a force unadopt site button (for admin users only) that allows admins to force a user to unadopt a site
Check that the force unadopt button appears only when the users is admin and successfully unadopts the given site, even if the admin is not the site's adopter
> Connect force unadopt site route

- src/App.tsx
- src/containers/addSites/index.tsx
- src/containers/adminDashboard/index.tsx
- src/containers/email/index.tsx
- src/containers/reports/index.tsx
Redesign the admin dashboard to consolidate admin features in one page
- Refactors the add site forms into a new page
- Move promote user/child account form into modals within buttons
- Add links to admin features under dashboard
Dashboard: 
Promote user modal:
Child account modal:
> Ah.admin redesign

- src/api/test/protectedApiClient.test.ts
- src/components/careEntry/index.tsx
- src/components/forms/stewardshipForm/index.tsx
- src/containers/reports/ducks/types.ts
- src/containers/reports/test/selectors.test.ts
- src/containers/treePage/ducks/types.ts
- src/containers/treePage/index.tsx
- src/containers/treePage/test/reducers.test.ts
- src/containers/treePage/test/selectors.test.ts
- src/containers/treePage/test/thunks.test.ts
- src/i18n/en/forms.json
- src/i18n/en/treePage/careEntry.json
- src/utils/stringFormat.tsx
- src/utils/test/stringFormat.test.ts
[GH Projects Ticket](https://github.com/Code-4-Community/speak-for-the-trees-frontend/issues/255)
Resolves #255 
See also https://github.com/Code-4-Community/speak-for-the-trees-backend-v2/pull/193
Add a new stewardship activity "installed watering bag" for use in the frontend
- Update record/edit stewardship methods to send watering bag status
- Update `generateTreeCareMessage` to display watering bag status
- Add `installedWateringBag` field to request objects
- Verified recording/editing stewardships correctly sends watering bag status
- Verified tree page correctly displays watering bag status in stewardship message
- Verified reports correctly show watering bag status, and exported CSV contains correct watering bag status
> add new stewardship activity

- src/api/protectedApiClient.ts
- src/api/test/protectedApiClient.test.ts
- src/components/careEntry/index.tsx
- src/components/forms/updateSiteForm/index.tsx
- src/components/siteEntryTable/index.tsx
- src/components/themedComponents/index.tsx
- src/containers/sitePage/index.tsx
- src/containers/treePage/ducks/types.ts
- src/containers/treePage/test/reducers.test.ts
- src/containers/treePage/test/selectors.test.ts
- src/containers/treePage/test/thunks.test.ts
- src/i18n/en/forms.json
- src/i18n/en/site.json
- src/i18n/en/treePage/types.json
- src/utils/test/stringFormat.test.ts
- src/utils/test/treeFunctions.test.ts
[GH Projects Ticket](https://github.com/orgs/Code-4-Community/projects/15/views/1?pane=issue&itemId=29884931)
Connect the edit site entry route with the frontend to allow admins to edit properties of existing site entries through the site page (http://localhost:3000/site/:site_id)
Backend PR [here](https://github.com/Code-4-Community/speak-for-the-trees-backend-v2/pull/186)
Add a new column to the site entries table on the site page that admins can click to bring up a modal where they can edit an existing site entry.
While doing this, I also had to add a new column to the `SITE_ENTRIES` table, `CREATED_AT`, that keeps track of when the site entry was initially added so that the existing `UPDATED_AT` column can be used to keep track of when the site entry was updated last.
Site entries …
> Connect edit site entry route with frontend

- src/components/treeInfo/index.tsx
- src/components/treePageHeader/index.tsx
See https://github.com/Code-4-Community/speak-for-the-trees-backend-v2/pull/196
Hide adopt buttons and stewardship form if a site does not have a tree present
- Verified the adopt buttons/stewardship form don't show if there is no tree present at the site
- Verified above components do show if there is a tree present
> Ah.prevent open adoption

- src/components/navBar/index.tsx
Todo: look into routing to HOME when not on sign up or login
Resolves #236 
This ticket resolves being able to move to the map page when users are not signed it. Previously, the SFTT logo in the NavBar redirected users to the home page, which we are in progress to remove. Additionally, when users are not signed in, a redirect to the home page would redirect to login/signup. As such, there was no clear path to the landing map page from login/signup.
This change allows the SFTT logo to be used as a redirect and bring users straight to the map page. We changed the NavBar SFTT Logo redirect from Routes.HOME to Routes.LANDING. Note that this change affects all pages (not just sign up and login), and that the HOME page is being deprecated. …
> Allow users to return to map page if not logged in #236

- src/api/protectedApiClient.ts
- src/api/test/protectedApiClient.test.ts
- src/components/careEntry/index.tsx
- src/components/confirmationModal/index.tsx
- src/components/themedComponents/index.tsx
- src/components/treePage/siteImageCarousel.tsx
- src/containers/treePage/ducks/types.ts
- src/containers/treePage/test/selectors.test.ts
This is a duplicate of https://github.com/Code-4-Community/speak-for-the-trees-frontend/pull/303 to fix build issues
Resolves #288 
This ticket adds the delete button to site images, allowing users to delete uploaded images. This keeps our site clean, to avoid irrelevant and incorrect images from staying online.
This change both adds delete functionality to the client, but adds a UI component to actually add an image. This deletion occurs both in AWS and the database (as dictated by the backend)
We manually tested this by:
- Uploading an image on the branch SK.CL.upload-site-image
- Opening AWS > sftt-user-uploads > ... > image folder, ensuring that the image exists
- Clicking the delete button
- Checking that AWS no longer had the image
- Checking that the database site_images folder no …
> Move delete site image functionality to clean branch

- src/components/navBar/mobileNavBar/index.tsx
- src/components/navBar/navExtra/index.tsx
- src/components/navBar/translationDropdown.tsx
Resolves #234
Provides a dropdown button for users to switch languages (if available)
removed FlexBar component from mobileNavBar, replaced with Flex. There is still some weird alignment issue with the button, so that needs to be fixed
Ran the frontend, changed languages successfully
> Ot.language options

- craco.config.js
- package.json
- setup.js
- src/components/forms/sendEmailForm/index.tsx
- src/i18n/en/forms.json
- yarn.lock
Resolves #275 
On the emailer page, add a toggle to preview email HTML before sending
- Add DOMpurify as a dependency to sanitize HTML
- Add a switch to toggle between the raw HTML editor and email previewing 
Raw view:
Preview view:
- Verified the switch toggles between raw and preview views
- Verified HTML content is sanitized in the preview view
> Emailer: preview HTML content before sending

- src/components/mapComponents/mapDisplays/selectorMapDisplay/index.tsx
- src/components/mapComponents/maps/mapWithPopup/index.tsx
- src/components/mapComponents/maps/selectorMap/index.tsx
- src/containers/treePage/index.tsx
Resolves #325
This change adds a map to the tree info page, allowing users to see where the tree exists relative to other trees and the entire map of Boston
DUPLICATED IN https://github.com/Code-4-Community/speak-for-the-trees-frontend/pull/337
Changes include
- Adding a map height parameter to make the height of the map component specifiable depending on where it is called from
- Adding sites and neighborhoods fields to tree props so that the map component can display the entire map of all other sites
- Define a state for the map marker and position
- Add the actual map component to a tree page
To verify that this works
- Select a site from the home page
- Select 'More Info', open in a new tab
- Note that a map exists on the more info page
- Ensure that the map position on the tree page …
> Sk.add map to tree page

- src/components/mapComponents/mapDisplays/selectorMapDisplay/index.tsx
- src/components/mapComponents/maps/mapWithPopup/index.tsx
- src/components/mapComponents/maps/selectorMap/index.tsx
- src/containers/treePage/index.tsx
Resolves #325
This change adds a map to the tree info page, allowing users to see where the tree exists relative to other trees and the entire map of Boston
DUPLICATE OF https://github.com/Code-4-Community/speak-for-the-trees-frontend/pull/327
Changes include
- Adding a map height parameter to make the height of the map component specifiable depending on where it is called from
- Adding sites and neighborhoods fields to tree props so that the map component can display the entire map of all other sites
- Define a state for the map marker and position
- Add the actual map component to a tree page
To verify that this works
- Select a site from the home page
- Select 'More Info', open in a new tab
- Note that a map exists on the more info page
- Ensure that the map position on the tree page …
> Sk.add map to tree page fix build

- src/containers/treePage/index.tsx
Resolves #325
This change adds a map to the tree info page, allowing users to see where the tree exists relative to other trees and the entire map of Boston
ADDITION TO
https://github.com/Code-4-Community/speak-for-the-trees-frontend/pull/337
https://github.com/Code-4-Community/speak-for-the-trees-frontend/pull/327
Changes include
- Adding a map height parameter to make the height of the map component specifiable depending on where it is called from
- Adding sites and neighborhoods fields to tree props so that the map component can display the entire map of all other sites
- Define a state for the map marker and position
- Add the actual map component to a tree page
To verify that this works
- Select a site from the home page
- Select 'More Info', open in a new tab
- Note that a map …
> Add dispatch to fix tree page map buffering

- src/components/mapComponents/mapDisplays/selectorMapDisplay/index.tsx
- src/components/mapComponents/maps/mapWithPopup/index.tsx
- src/components/mapComponents/maps/selectorMap/index.tsx
- src/containers/treePage/index.tsx
Resolves #325
This change adds a map to the tree info page, allowing users to see where the tree exists relative to other trees and the entire map of Boston
Changes include
- Adding a map height parameter to make the height of the map component specifiable depending on where it is called from
- Adding sites and neighborhoods fields to tree props so that the map component can display the entire map of all other sites
- Define a state for the map marker and position
- Add the actual map component to a tree page
To verify that this works
- Select a site from the home page
- Select 'More Info', open in a new tab
- Note that a map exists on the more info page
- Ensure that the map position on the tree page matches the tree position on the home page
> Move add map changes to new PR, add map to tree page fixing dispatch and merge conflict

- src/api/protectedApiClient.ts
- src/api/test/protectedApiClient.test.ts
- src/components/forms/reportSiteForm/index.tsx
- src/components/reportSiteButton/index.tsx
- src/components/treePage/treeInfo.tsx
- src/containers/treePage/ducks/types.ts
- src/containers/treePage/index.tsx
- src/i18n/en/forms.json
- src/i18n/en/treePage/treePage.json
Allows users to make report a site for issues: incorrect information displayed, or inappropriate content (tree name/pictures)
See also: https://github.com/Code-4-Community/speak-for-the-trees-backend-v2/pull/230
- Adds the `ReportSiteButton` and `ReportSiteForm` components to allow for site reporting
- Stub `siteData` prop on the tree page
- Map on page needs to load every site marker even though only a small portion is shown, which dramatically slows down the page - temporary fix until we figure out how to make the map more performant
Button on page:
Form in modal:
- Verified submitting is disabled when no reason is given
- Verified submitting form calls API route to send report email
> Add User Site Reporting to Tree Page

- src/components/treePage/treeInfo.tsx
- src/i18n/en/maps.json
> fix json + duped button
